link:https://commons.wikimedia.org/wiki/File:Berner_Fachhochschule_Logo_small.svg[image:https://upload.wikimedia.org/wikipedia/commons/2/25/Berner_Fachhochschule_Logo_small.svg[Logo BFH - Bern University of Applied Sciences]]

= Modulkonzept

== Software Engineering (WSEG)

=== Autor: Jörg Berkel

=== link:https://semver.org[Version]: 1.0.6

=== Gültig ab: HS 2026 (1.8.2026)

== Formale Beschreibung

[cols=">,1"] 
|===

| Modulname und -kürzel 
| WSEG - Software Engineering

| Verantwortliches Institut, ggfs. Fachgruppe
| https://www.bfh.ch/de/forschung/forschungsbereiche/public-sector-transformation/[Institut Public Sector Transformation (IPST)], https://www.bfh.ch/de/forschung/forschungsbereiche/digital-sustainability-lab/[Digital Sustainability Lab]

| Studiengang
| https://bfh.ch/bachelor-digitalbusiness-ai[Bachelor in Digital Business & AI]

| Stufe
| Hauptstudium

| ggfs. Vertiefung / Wahlpflichtgruppe
| n/a

| Semester
| 3. Semester Vollzeit, 4. Semester Teilzeit

| Durchführungsmodus & Hinweise für Stundenplan
| Jede Woche 4-Lektionenblock

| ECTS-Credits
| 6 ECTS (180 Stunden)

| Sprache
| Deutsch

| Zielgruppe inkl. Eignung für Incoming-Stud.
| primär ausgerichtet auf BWI-Studierende
offen für Studierende anderer Studiengänge oder Incoming-Studierende (mit Interesse an Open Source Software)

|
|===

== Inhaltliche Beschreibung

[cols=">,1"] 
|===

| Kurzbeschreibung +
(öffentlich, für IS-A) 
| Im Modul "Software Engineering" lernen die Studierenden, wie sie in einer Gruppe agil Software entwickeln. Das Modul beinhaltet theoretische Inhalte, sowie ein semesterbegleitendes Praxisprojekt pro Gruppe, an dem die Studierenden das Gelernte anwenden und selbständig vertiefen. Im Praxisprojekt geht es neben der Programmierung und dem Einsatz von standardisierten Webtechnologien darum, gemeinsam ein wertschöpfendes Produkt (bzw. Minimal Viable Product) zu gestalten und DevOps-Praktiken rund um Gitlab kennenzulernen.

| Detaillierte Beschreibung 
| siehe Modulinhalte und Vermittelte Kompetenzen

| Modulinhalte und Zusammenarbeit +
(Modulaufbau, Fachinhalte, Methoden, Praxisfälle, Forschungsbezug)
a| Modulaufbau
wöchentlicher 4-Lektionenblock während des Semesters mit einer Durchführung pro Klasse.
Der 4-Lektionenblock besteht aus theoretischen (⅓) und praktischen Inhalten (⅔).

Zentrale Inhalte

- Grundlagen Softwareentwicklung
- Praxisprojekt: Entwicklung einer Web-Applikation mit Frontend und Backend (z.B. mit https://vuejs.org/[Vue.js] und https://strapi.io/[Strapi])
- Agile Softwareentwicklung im Team
- Grundlagen Objektorientierter Programmierung, Verwendung von REST APIs
- Kennenlernen und Einsatz von Werkzeugen wie z.B. GitLab zur Quellcodeverwaltung/Dokumentation und IDEs wie VSCodium (Visual Studio Code) im Zusammenspiel mit AI-Coding-Agents wie OpenCode

Methoden
Lesen, Verstehen und Besprechen von Lehrbuchtexten, Fachartikeln und Softwaredokumentationen
Lösen von Entwicklungsaufgaben durch die Dozierenden, durch einzelne Studierende und durch Gruppen von vier bis fünf Studierenden

Praxisfälle
aus der Arbeitserfahrung der beteiligten Dozierenden und Gäste

Forschungsbezug
aus der Forschungserfahrung der beteiligten Dozierenden und Gäste

| Lehr- und Lernformen
| Präsenzstudium
Wissenserarbeitung, Entwicklungsaufgaben, Lehrgespräch, Coaching

Selbststudium
Literaturstudium, Videos, Projektarbeit: Einzel-/Gruppenarbeiten

| Literatur
| Sommerville, I. (2020): Modernes Software-Engineering. Entwurf und Entwicklung von Softwareprodukten. Pearson Deutschland. ISBN: 978-3868943962.

Sommerville, I. (2020): Engineering Software Products: An Introduction to Modern Software Engineering, Global Edition. Pearson Education. ISBN: 978-1292376349.

| Eingangskompetenzen +
(Fachkompetenzen und Kompetenzen gemäss Kompetenzmodell BFH-W)
| Fachkompetenzen und Kompetenzen der Berufsmaturität der Typen «Technik, Architektur, Life Sciences» oder «Wirtschaft und Dienstleistungen»

| Vermittelte Kompetenzen +
(Fachkompetenzen und Kompetenzen gemäss Kompetenzmodell BFH-W)
a| +++Fachkompetenzen:+++ Die Studierenden können...

- in einer Kleingrupe aus einer eigenen Produktidee ein Konzept für eine Onlineplattform erstellen und daraus als Team während eines Semesters einen funktionalen Softwareprototypen als „Single Page Application“ entwickeln.
- Grundbegriffe und Herausforderungen des modernen Software Engineerings im Bereich „Webtechnologien“ erklären und Phasen und Aktivitäten in der Entwicklung von Softwareprodukten beschreiben.
- auf dem eigenen Arbeitsgerät eine lokale Entwicklungsumgebung einrichten und Werkzeuge zur arbeitsteiligen Entwicklung von Softwareprodukten einsetzen (Quellcodeverwaltung mit Git).
- die Prinzipien agiler Arbeitsweisen praktisch umsetzen und deren Ergebnisse (Review, Planning, Retrospective) in regelmässigen Kurzpräsentationen demonstrieren. 
- die Dokumentationen eingesetzter Webtechnologien und -frameworks konsultieren und Probleme per Internetrecherche oder durch Einsatz von Large Language Models lösen.
- funktionale und nichtfunktionale Qualitätsmerkmale von Softwareprodukten beschreiben und Techniken zur Komplexitätsreduktion einer Software erklären.
- Projektdokumentation und -artefakte in einem Git-Repository ablegen und dazu eine Continous-Integration-Automatisierung einrichten welche diese für Aussenstehende sichtbar publiziert.

+++Kompetenzen gemäss Kompetenzmodell BFH-W:+++

Problemsolving/Design Thinking (verwandt: Methodenkompetenz): Die Studierenden...

- erfahren durch die eigene Praxis, dass im Software Engineering eine Kombination von kreativ-spielerischem und logisch-stringentem Vorgehen zielführend ist.

Kollaboration (verwandt: Sozialkompetenzen): Die Studierenden...

- erleben und reflektieren die Voraussetzungen für eine erfolgreiche, effiziente und effektive Zusammenarbeit.
- bringen ihre persönlichen Ressourcen in Teams ein.
- kommunizieren als Team mit Aussenstehenden durch Präsentationen und schriftliche Beiträge

Selbstmanagement (verwandt: Selbstkompetenzen): Die Studierenden...

- lernen mit Autonomie und Selbstorganisation umzugehen.
- lernen und arbeiten selbständig, erkennen Kenntnislücken frühzeitig und füllen diese selbständig oder suchen sich Unterstützung bei Peers oder Coaches.
- können ihre Denk- und Arbeitsprozesse kritisch hinterfragen und mögliche Handlungsoptionen entwickeln.
- entwickeln realistische Selbst- und Zeiteinschätzungen.

Umgang mit Komplexität: Die Studierenden...

- reflektieren die Komplexität von modernen, verteilten Softwareanwendungen im Bereich Webtechnologien.
- reflektieren die Komplexität von arbeitsteiliger Softwareentwicklung.

| Schnittstellen zu anderen Modulen +
(zuführende, parallele, weiterführende)
a| baut auf folgenden Pflichtmodulen auf

- https://github.com/digital-sustainability/module-wsen[WSEN] Softwareentwicklung, Grundlagen Programmieren
- WDDA Data Management & Data Analysis, Datenmodelle
- WREQ Requirements Engineering, RE & UML

Wahlpflichtmodule mit Beispiel

- EWEB Web Engineering, Webtechnologien
- ERAP Hackathon & Rapid Prototyping, APIs bauen/verwenden
- https://github.com/digital-sustainability/module-eoss[EOSS] Open Source Software
Management, Softwarelizenzen/Git
- EUID Hands-on UI Design, UX/UI Design
- ECYS Cybersecurity, Authentifikation

Vertiefung

- SDA1,2,3,4 Software Design & Architecture

| Präsenzpflicht
| keine Präsenzpflicht

| Kompetenznachweis
a| Teil 1: Projektabgabe mit Zwischenergebnissen (Agile Rituale, Deliverables, Abschlusspräsentation) als Gruppenarbeit mit gemeinsamer Note (60%) in den Semesterwochen:

- SW 5: Agiles Wrap-up und Deliverable 1
- SW 8: Agiles Wrap-up und Deliverable 2
- SW 11: Agiles Wrap-up und Deliverable 3
- SW 14: Abschlusspräsentation: Live-Demo und Retrospektive 
- SW 15: Projektabgabe und Deliverable 4

Teil 2: Schlussprüfung (40%), Moodle-Prüfung und praktische Aufgaben, 90 Minuten

- In den offiziellen Prüfungswochen
- elektronische PC-Prüfung mit https://www.lernstick.ch/[Lernstick] und https://www.campla.ch/[CAMPLA]

Gemäss RRS Art. 11 müssen alle Teilkompetenznachweise bestanden sein.
Die Teilkompetenznachweise werden auf halbe Noten gerundet.

Hilfsmittel bei schriftlicher Prüfung

- Open Book, erweitert durch digitale Dokumente hochgeladen auf CAMPLA
- Wörterbuch Muttersprache - Sprache Kompetenznachweis
- BFH-Taschenrechner

| Bemerkungen
| Sämtliche Inhalte sind unter https://github.com/digital-sustainability/module-wseg
unter CC-BY 4.0 als OER veröffentlicht.
|
|===

== Anhang

=== Semesterablauf

image::https://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/digital-sustainability/module-wseg/26/fs/docs/timing.puml[timing]

=== Zweck des Dokuments

Das Modulkonzept dient dem gemeinsamen Verständnis aller an einem Modul Beteiligen bezüglich Inhalte, Didaktik und Tools. Es ist das zentrale Dokument beim Aufbau und bei Überarbeitungen von Modulen. Darüber hinaus hat es aber weitere Zielgruppen:

•	Dozierende/WMAs anderer Module: zum Aufbau und zur Abgrenzung von eigenen Modulinhalten, zum Angebot eines ausgewogenen Mixes von didaktischen Methoden sowie für einen koordinierten Einsatz von Tools
•	Studiengangsleitende: für die Kenntnis von Ansprechpartnern sowie zur Koordination von Modulinhalten, Didaktikvielfalt und Tooleinsatz
•	Instituts-, Abteilungs- und Fachgruppenleitende: zur Festlegung der Zuständigkeiten, für organisationsübergreifende Zusammenarbeit sowie zur Förderung von Themen der jeweiligen Organisationseinheiten

Die Studierenden sind keine direkte Zielgruppe des Modulkonzepts. In der Regel werden Ihnen nur Auszüge aus dem Konzept zur Verfügung gestellt; diese werden in die Modulbeschreibung auf IS-Academia übertragen. Die einzelnen Blöcke der Modulbeschreibung in IS-Academia sollen möglichst direkt aus dem Modulkonzept übernommen werden.

Das Modulkonzept wird im Rahmen des Neuaufbaus eines Moduls erstellt und bei Überarbeitungen angepasst. Zu jedem Zeitpunkt soll eine aktuelle Version verfügbar sein.

Die in der Vorlage zum Modulkonzept enthaltenen Blöcke sind Pflichtbausteine, zusätzliche Blöcke sind möglich. Diese sollen direkt im Konzept und nicht in separaten Dokumenten ergänzt werden.
