@startuml
Title Semester - Timing
header: FS24
footer: "https://github.com/digital-sustainability/module-wseg/blob/24/fs/docs/timing.puml"
caption CC-BY-4.0

legend
X-Axis: (relative) week numbers

PRP Preparation
end legend

concise "Module WSEG" as module
robust "Studierende" as studi
concise "Deliverables" as tasks
concise "Dozent" as dozent
scale 1 as 80 pixels

@-1
studi is EINGESCHRIEBEN
dozent is supporting

@+1
tasks is Start

@1
dozent -> module: Treffen
module is "1"
tasks is "Pitch-Präsentation"
studi is "GRUPPEN & Kick-Off"

@+1
dozent -> module: Treffen
module is "2"
studi is "Web"

@+1
dozent -> module: Treffen
module is "3"
studi is "Code"
@7 <-> @11 : {10 x 5-10 min Vorstellung(en)}

@+1
dozent -> module: Treffen
module is "4"
studi is "Architektur"

@+1
dozent -> module: Treffen
module is "5"
tasks is "Blog"
studi is "Objektorientierung"

@+1
module is "OSTERN"

@+2
dozent -> module: BBB
module is "6"
studi is "Agilität"

@+1
dozent -> module: Treffen
module is "7"
tasks is "Zwischenpräsentation"
studi is "Coaching"

@+1
dozent -> module: Treffen
module is "8 "
studi is "DevOps 1"

@+1
dozent -> module: Treffen
module is "9"
studi is "Testing"
tasks is "Blog mit GitLab Pages"

@+1
module is "Ausfall"
studi is "Cloud"

@+1
dozent -> module: Treffen
module is "11"
studi is "UX"

@+1
dozent -> module: BBB
module is "12"
studi is "DevOps 2"
tasks is "Abschluss"

@+1
dozent -> module: Treffen
module is "13"
studi is "Abschluss"

@+1
dozent -> module: Treffen
module is "14"
studi is "Präsentation"

@+1
module is {-}
tasks is {-}

@+1
module is Vorbereitung

@+1
dozent is {-}

@+1
module -> studi: Prüfung
module is {-}

highlight 1.5 to 2 #lightgreen : PRP
highlight 2.5 to 3 #lightgreen : PRP
highlight 3.5 to 4 #lightgreen : PRP
highlight 4.5 to 5 #lightgreen : PRP
highlight 5.5 to 6 #lightgreen : PRP
highlight 8.5 to 9 #lightgreen : PRP

@enduml
